# TCL File Generated by Component Editor 25.1
# Sun Dec 07 22:58:38 MST 2025
# DO NOT MODIFY


# 
# JP1_PIO "JP1_PIO" v1.0
#  2025.12.07.22:58:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module JP1_PIO
# 
set_module_property DESCRIPTION ""
set_module_property NAME JP1_PIO
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME JP1_PIO
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

